"""Answer synthesis from retrieved documents using Claude + RAG.

This module takes retrieved document chunks and uses Claude to:
1. Synthesize a coherent answer to the user's question
2. Extract and verify citations
3. Suggest follow-up questions for drill-down exploration

PM Context: After searching for relevant lease or report sections, we need to
synthesize a natural language answer. Instead of returning raw document snippets,
Claude reads the chunks and generates a fluent answer with proper citations.

Example flow:
- User: "What are the tenant maintenance obligations?"
- Search returns: 3 relevant lease sections
- Claude reads sections and generates: "The tenant must maintain the unit in
  good condition, including..." with citations to specific lease sections
"""

import logging
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
import re

import anthropic

from .document_processor import DocumentChunk
from ..access_control.rbac import UserContext

logger = logging.getLogger(__name__)


@dataclass
class Citation:
    """Source citation for a claim in the answer.
    
    Attributes:
        source_doc: Document title or name
        page_number: Page number in document
        chunk_id: Specific chunk ID for linking
        quote: Relevant quote from source
    """
    source_doc: str
    page_number: int
    chunk_id: str
    quote: str


@dataclass
class AugmentedAnswer:
    """Complete answer to user query with citations and follow-ups.
    
    Attributes:
        answer_text: The main answer (synthesized by Claude)
        sources: List of Citation objects
        confidence: Confidence score based on retrieval quality (0.0-1.0)
        follow_up_questions: Suggested follow-up questions for the user
    
    Example:
        >>> answer = AugmentedAnswer(
        ...     answer_text="The tenant must maintain the unit...",
        ...     sources=[Citation(...), Citation(...)],
        ...     confidence=0.92,
        ...     follow_up_questions=["What's the process for maintenance requests?"]
        ... )
    """
    answer_text: str
    sources: List[Citation] = field(default_factory=list)
    confidence: float = 0.7
    follow_up_questions: List[str] = field(default_factory=list)


def format_context_window(chunks: List[DocumentChunk]) -> str:
    """Prepare document chunks for Claude context window.
    
    Args:
        chunks: List of retrieved DocumentChunk objects
    
    Returns:
        Formatted string with chunks and metadata
    
    Format:
        [Document: Lease #001 | Page 2 | Section: tenant_obligations]
        Tenant shall maintain the unit in good condition...
        
        [Document: Lease #001 | Page 3 | Section: maintenance_requests]
        ...
    
    Note:
        Claude has 128k token context, so we can include 50+ pages of documents.
        We prioritize by relevance_score.
    """
    formatted = "RETRIEVED DOCUMENTS:\n\n"
    
    for i, chunk in enumerate(chunks, 1):
        metadata = chunk.metadata or {}
        doc_type = metadata.get('doc_type', 'document')
        
        formatted += f"[{i}. {doc_type.upper()} | Page {chunk.page_number} | Section: {chunk.section}]\n"
        formatted += chunk.chunk_text[:500] + "\n"  # Truncate very long chunks
        formatted += f"[Source ID: {chunk.chunk_id}]\n\n"
    
    return formatted


def extract_citations(answer: str, chunks: List[DocumentChunk]) -> List[Citation]:
    """Extract and verify citations in Claude's answer.
    
    Claude may mention documents by metadata (page numbers, section names).
    This function:
    1. Identifies claims that need citations
    2. Maps them to source chunks
    3. Extracts relevant quotes
    4. Returns structured Citation objects
    
    Args:
        answer: Answer text generated by Claude
        chunks: Original chunks that were provided as context
    
    Returns:
        List of Citation objects
    
    Example:
        >>> answer = "According to the lease (page 2), tenant must maintain the unit."
        >>> citations = extract_citations(answer, chunks)
        >>> for c in citations:
        ...     print(f"Page {c.page_number}: {c.quote}")
    """
    citations = []
    
    # Look for page references in answer
    page_pattern = r'(?:page|pg)\s*(\d+)'
    for match in re.finditer(page_pattern, answer, re.IGNORECASE):
        page_num = int(match.group(1))
        # Find chunk from that page
        matching_chunk = next((c for c in chunks if c.page_number == page_num), None)
        if matching_chunk:
            citations.append(Citation(
                source_doc=matching_chunk.metadata.get('doc_type', 'Document'),
                page_number=page_num,
                chunk_id=matching_chunk.chunk_id,
                quote=matching_chunk.chunk_text[:100]
            ))
    
    # Look for section references
    section_pattern = r'(?:section|clause)\s*["\']?([a-z_]+)["\']?'
    for match in re.finditer(section_pattern, answer, re.IGNORECASE):
        section_name = match.group(1)
        # Find chunk from that section
        matching_chunk = next((c for c in chunks if c.section == section_name), None)
        if matching_chunk and not any(ct.chunk_id == matching_chunk.chunk_id for ct in citations):
            citations.append(Citation(
                source_doc=matching_chunk.metadata.get('doc_type', 'Document'),
                page_number=matching_chunk.page_number,
                chunk_id=matching_chunk.chunk_id,
                quote=matching_chunk.chunk_text[:100]
            ))
    
    logger.info(f"Extracted {len(citations)} citations from answer")
    return citations


def suggest_follow_ups(query: str, answer: str) -> List[str]:
    """Generate follow-up questions for deeper exploration.
    
    Uses Claude to generate natural follow-up questions based on the
    original query and answer provided.
    
    Args:
        query: Original user query
        answer: Claude-generated answer
    
    Returns:
        List of 2-3 suggested follow-up questions
    
    Example:
        >>> query = "What are maintenance obligations?"
        >>> answer = "The tenant must maintain..."
        >>> followups = suggest_follow_ups(query, answer)
        >>> for q in followups:
        ...     print(f"- {q}")
    
    Note:
        These are shown in the UI as suggestions, allowing users to
        drill deeper without retyping questions.
    """
    client = anthropic.Anthropic()
    
    prompt = f"""Based on this question and answer, suggest 2-3 follow-up questions
    a property manager might ask next.

Original Question: {query}

Answer: {answer[:500]}

Generate follow-ups that naturally extend this conversation, like:
- Asking about exceptions or special cases
- Asking about process or timeline
- Asking about costs or responsibilities

Respond with only the questions, one per line, without numbering."""
    
    try:
        message = client.messages.create(
            model="claude-3-5-sonnet-20241022",
            max_tokens=200,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        
        response_text = message.content[0].text.strip()
        followups = [q.strip() for q in response_text.split('\n') if q.strip()]
        logger.debug(f"Generated {len(followups)} follow-up questions")
        return followups[:3]  # Return top 3
    
    except Exception as e:
        logger.warning(f"Follow-up generation failed: {e}")
        return []


def generate_answer(
    query: str,
    retrieved_chunks: List[DocumentChunk],
    user_context: UserContext
) -> AugmentedAnswer:
    """Generate a complete augmented answer from retrieved chunks.
    
    Args:
        query: User's original question
        retrieved_chunks: List of DocumentChunk from search_documents()
        user_context: UserContext (for logging/audit)
    
    Returns:
        AugmentedAnswer with answer text, citations, confidence, follow-ups
    
    Process:
        1. Format chunks as context for Claude
        2. Call Claude to synthesize answer
        3. Extract citations from answer
        4. Generate follow-up questions
        5. Calculate confidence based on retrieval quality
        6. Return AugmentedAnswer
    
    Example:
        >>> ctx = UserContext("user1", "tenant1", "pm", [])
        >>> chunks = search_documents("maintenance obligations", ctx)
        >>> answer = generate_answer("What are maintenance obligations?", chunks, ctx)
        >>> print(answer.answer_text)
        >>> for src in answer.sources:
        ...     print(f"Source: {src.source_doc} p.{src.page_number}")
    
    Confidence:
        - Based on number and quality of retrieved chunks
        - 0.7-0.8: Single source
        - 0.8-0.9: Multiple sources
        - 0.9+: Strong consensus across multiple sources
    """
    if not retrieved_chunks:
        return AugmentedAnswer(
            answer_text="I don't have any documents available to answer this question.",
            sources=[],
            confidence=0.0,
            follow_up_questions=[]
        )
    
    client = anthropic.Anthropic()
    
    # Step 1: Format context
    context_window = format_context_window(retrieved_chunks)
    
    # Step 2: Generate answer
    system_prompt = """You are a real estate portfolio intelligence assistant.
    
Your job is to answer questions about properties, leases, and maintenance based on
the provided documents.

When answering:
- Be direct and factual
- Include specific details from documents (page numbers, sections)
- Note if information is missing or unclear
- Use clear, professional language
- Keep answers to 2-3 paragraphs max"""
    
    user_message = f"""Question: {query}

{context_window}

Please answer the question based on the provided documents. Include references to
the source documents (e.g., "According to the lease on page 2...")"""
    
    try:
        message = client.messages.create(
            model="claude-3-5-sonnet-20241022",
            max_tokens=1000,
            system=system_prompt,
            messages=[
                {"role": "user", "content": user_message}
            ]
        )
        
        answer_text = message.content[0].text.strip()
        
        # Step 3: Extract citations
        citations = extract_citations(answer_text, retrieved_chunks)
        
        # Step 4: Generate follow-ups
        follow_ups = suggest_follow_ups(query, answer_text)
        
        # Step 5: Calculate confidence
        # Based on number of sources and their relevance scores
        avg_relevance = sum(
            getattr(c, 'relevance_score', 0.5) for c in retrieved_chunks
        ) / len(retrieved_chunks) if retrieved_chunks else 0.5
        
        confidence = min(0.99, 0.5 + (len(retrieved_chunks) * 0.1) + (avg_relevance * 0.3))
        
        result = AugmentedAnswer(
            answer_text=answer_text,
            sources=citations,
            confidence=confidence,
            follow_up_questions=follow_ups
        )
        
        logger.info(f"Generated answer with confidence {confidence:.2f} from {len(retrieved_chunks)} chunks")
        return result
    
    except Exception as e:
        logger.error(f"Answer generation failed: {e}")
        return AugmentedAnswer(
            answer_text=f"I encountered an error generating an answer: {e}",
            sources=[],
            confidence=0.0,
            follow_up_questions=[]
        )
